#######
# Compiled from data/horsetastic/functions/loot.mcscript
# to .//data/horsetastic/functions/loot/skeleton_horse.mcfunction
#
# Generated by Minecraft Script for 1.13
######
loot spawn ~ ~ ~ loot horsetastic:entities/skeleton_horse