#######
# Compiled from data/horsetastic/functions/loot.mcscript
# to .//data/horsetastic/functions/loot/undead.mcfunction
#
# Generated by Minecraft Script for 1.13
######
loot spawn ~ ~ ~ loot horsetastic:entities/undead
