#######
# Compiled from data/horsetastic/functions/crafting.mcscript
# to .//data/horsetastic/functions/crafting/whip/blinky/1.mcfunction
#
# Generated by Minecraft Script for 1.13
######
replaceitem block ~ ~ ~ container.16 minecraft:carrot_on_a_stick{CustomModelData:703002,display:{Name:"{\"text\":\"Whip\",\"color\":\"dark_purple\",\"italic\":\"false\"}",Lore:["{\"text\":\"Use to teleport to Blinky\",\"color\":\"dark_green\",\"italic\":\"false\"}"]},HideFlags:1,Enchantments:[{id:"minecraft:unbreaking",lvl:1}],horsetastic:{id:"blinky_whip"}} 1
tag @s add ac_lib_keep_1
tag @s add ac_lib_advanced_crafter_crafted
tag @s add ac_lib_advanced_crafter_crafted_blinky_whip
