#######
# Compiled from data/horsetastic/functions/crafting.mcscript
# to .//data/horsetastic/functions/crafting/whip/blinky/2.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function ac_lib:advanced_crafter/crafted
replaceitem block ~ ~ ~ container.2 minecraft:saddle{CustomModelData: 703103,horsetastic:{id:"blinky_saddle"},HideFlags:1,display:{Lore:["{\"text\":\"Drop to summon Blinky\",\"color\":\"dark_green\",\"italic\":\"false\"}"],Name:"{\"text\":\"Blinky's saddle\",\"color\":\"dark_purple\",\"italic\":\"false\"}"},Enchantments:[{lvl:1,id:"minecraft:unbreaking"}]}
tag @s remove ac_lib_advanced_crafter_crafted
tag @s remove ac_lib_advanced_crafter_crafted_blinky_whip
