#######
# Compiled from data/horsetastic/functions/kill_horse.mcscript
# to .//data/horsetastic/functions/kill_horse_detect.mcfunction
#
# Generated by Minecraft Script for 1.13
######
#basic
execute as @e[type=horse,tag=horsetastic_horse_basic] at @s unless entity @s[nbt={SaddleItem: {id: "minecraft:saddle", Count: 1b, tag: {horsetastic:{id:"basic_saddle_"}}}}] run function horsetastic:kill_horse

#skeleton
execute as @e[type=skeleton_horse,tag=horsetastic_horse_skeleton] at @s unless entity @s[nbt={SaddleItem: {id: "minecraft:saddle", Count: 1b, tag: {horsetastic:{id:"skeleton_saddle_"}}}}] run function horsetastic:kill_horse

#blinky
execute as @e[type=skeleton_horse,tag=horsetastic_horse_blinky] at @s unless entity @s[nbt={SaddleItem: {id: "minecraft:saddle", Count: 1b, tag: {horsetastic:{id:"blinky_saddle_"}}}}] run function horsetastic:kill_horse
