#######
# Compiled from data/horsetastic/functions/kill_horse.mcscript
# to .//data/horsetastic/functions/kill_horse.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tp @p[distance=..1.5] ~ ~0.1 ~
tp @s ~ -500 ~