#######
# Compiled from /horsetastic/functions/load.mcscript
# to .//horsetastic/functions/load.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function horsetastic:mcscript/load


scoreboard objectives add saddle_og dummy "Saddle Ground Time"
scoreboard objectives add saddle_type dummy "Saddle Type"
scoreboard objectives add horse_whip_used minecraft.used:minecraft.carrot_on_a_stick "Whip used"