#######
# Compiled from data/horsetastic/functions/tick.mcscript
# to .//data/horsetastic/functions/tick.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function horsetastic:mark_ground_saddles/main
function horsetastic:summon_horse_auto/main
function horsetastic:replace_saddles/main
function horsetastic:kill_horse_detect
function horsetastic:crafting/main
function horsetastic:noai/main
function horsetastic:whip/main