#######
# Compiled from data/horsetastic/functions/tick.mcscript
# to .//data/horsetastic/functions/tick.mcfunction
#
# Generated by Minecraft Script for 1.13
######
#unnamedDE's Lib
execute unless score horsetastic installed_packs matches 1 run scoreboard players set horsetastic installed_packs 1
execute as @a at @s run function horsetastic:creative_menu/give
function horsetastic:mark_ground_saddles/main
function horsetastic:summon_horse_auto/main
function horsetastic:replace_saddles/main
function horsetastic:kill_horse_detect
function horsetastic:crafting/main
function horsetastic:noai/main
function horsetastic:whip/main
function horsetastic:visuals/main
effect give @a[nbt={RootVehicle:{Entity: {Tame: 1b, Invulnerable: 1b, id: "minecraft:skeleton_horse", Tags: ["horsetastic_horse_blinky"], CustomName: "{\"color\":\"dark_purple\",\"text\":\"Blinky\"}", SaddleItem: {id: "minecraft:saddle", Count: 1b, tag: {CustomModelData: 703103, display: {Lore: ["{\"text\":\"Remove to pick up Blinky\",\"color\":\"dark_green\",\"italic\":\"false\"}"], Name: "{\"text\":\"Blinky's saddle\",\"color\":\"dark_purple\",\"italic\":\"false\"}"}}}}}}] minecraft:resistance 1 4 true