#######
# Compiled from data/horsetastic/functions/management.mcscript
# to .//data/horsetastic/functions/uninstall.mcfunction
#
# Generated by Minecraft Script for 1.13
######
scoreboard objectives remove saddle_og
scoreboard objectives remove saddle_type
scoreboard objectives remove horse_whip_used
scoreboard objectives remove ht_creative_menu
execute if score datapack_list datapack_list matches 1.. run scoreboard players reset horsetastic datapack_list
