#######
# Compiled from /horsetastic/functions/summon_horse_manual.mcscript
# to .//horsetastic/functions/summon_horse_manual/basic.mcfunction
#
# Generated by Minecraft Script for 1.13
######
summon minecraft:horse ~ ~ ~ {Health:30f, Tame: 1b, Attributes: [{Base: 30.0d, Name: "generic.maxHealth"}, {Base: 0.2378785d, Name: "generic.movementSpeed"}, {Base: 0.7d, Name: "horse.jumpStrength"}], PersistenceRequired: 1b, Tags: ["horsetastic_horse_basic"], Variant: 513, DeathLootTable: "horsetastic:nothing", SaddleItem: {id: "minecraft:saddle", tag: {CustomModelData:703101,display:{Name:"{\"text\":\"Horse in a saddle's saddle\",\"color\":\"yellow\",\"italic\":\"false\"}",Lore:["{\"text\":\"Remove to pick up the horse\",\"color\":\"dark_green\",\"italic\":\"false\"}"]},HideFlags:1,Enchantments:[{id:"minecraft:unbreaking",lvl:1}]}, Count: 1b}}
