#######
# Compiled from data/horsetastic/functions/replace_saddles.mcscript
# to .//data/horsetastic/functions/replace_saddles/ground/blinky.mcfunction
#
# Generated by Minecraft Script for 1.13
######
data merge entity @s[type=minecraft:item] {Item:{id:"minecraft:saddle",Count:1b,tag:{CustomModelData:703103,display:{Name:"{\"text\":\"Blinky's saddle\",\"color\":\"dark_purple\",\"italic\":\"false\"}",Lore:["{\"text\":\"Drop to summon Blinky\",\"color\":\"dark_green\",\"italic\":\"false\"}"]},HideFlags:1,Enchantments:[{id:"minecraft:unbreaking",lvl:1}]}}}