#######
# Compiled from data/horsetastic/functions/replace_saddles.mcscript
# to .//data/horsetastic/functions/replace_saddles/ground/skeleton.mcfunction
#
# Generated by Minecraft Script for 1.13
######
data merge entity @s[type=minecraft:item] {Item:{id:"minecraft:saddle",Count:1b,tag:{CustomModelData:703102,display:{Name:"{\"text\":\"Skeleton Horse in a saddle\",\"color\":\"yellow\",\"italic\":\"false\"}",Lore:["{\"text\":\"Drop to summon a skeleton horse\",\"color\":\"dark_green\",\"italic\":\"false\"}"]},HideFlags:1,Enchantments:[{id:"minecraft:unbreaking",lvl:1}]}}}
