#######
# Compiled from data/horsetastic/functions/creative_menu.mcscript
# to .//data/horsetastic/functions/creative_menu/give.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if score @s ht_creative_menu matches 11 run give @s minecraft:saddle{horsetastic:{id:"basic_saddle"},CustomModelData:703101,display:{Name:"{\"text\":\"Horse in a saddle\",\"color\":\"yellow\",\"italic\":\"false\"}",Lore:["{\"text\":\"Drop it on the ground to summon a horse\",\"color\":\"dark_green\",\"italic\":\"false\"}"]},HideFlags:1,Enchantments:[{id:"minecraft:unbreaking",lvl:1}]} 1
execute if score @s ht_creative_menu matches 11 run scoreboard players reset @s ht_creative_menu

execute if score @s ht_creative_menu matches 12 run give @s minecraft:saddle{horsetastic:{id:"skeleton_saddle"},CustomModelData:703102,display:{Name:"{\"text\":\"Skeleton Horse in a saddle\",\"color\":\"yellow\",\"italic\":\"false\"}",Lore:["{\"text\":\"Drop to summon a skeleton horse\",\"color\":\"dark_green\",\"italic\":\"false\"}"]},HideFlags:1,Enchantments:[{id:"minecraft:unbreaking",lvl:1}]}
execute if score @s ht_creative_menu matches 12 run scoreboard players reset @s ht_creative_menu

execute if score @s ht_creative_menu matches 13 run give @p minecraft:saddle{horsetastic:{id:"blinky_saddle"},CustomModelData:703103,display:{Name:"{\"text\":\"Blinky's saddle\",\"color\":\"dark_purple\",\"italic\":\"false\"}",Lore:["{\"text\":\"Drop to summon Blinky\",\"color\":\"dark_green\",\"italic\":\"false\"}"]},HideFlags:1,Enchantments:[{id:"minecraft:unbreaking",lvl:1}]} 1
execute if score @s ht_creative_menu matches 13 run scoreboard players reset @s ht_creative_menu

execute if score @s ht_creative_menu matches 14 run give @s minecraft:carrot_on_a_stick{horsetastic:{id:"basic_whip"},CustomModelData:703001,display:{Lore:["{\"text\":\"Use to boost nearby horses\",\"color\":\"dark_green\",\"italic\":\"false\"}"],Name:"{\"text\":\"Whip\",\"color\":\"yellow\",\"italic\":\"false\"}"}} 1
execute if score @s ht_creative_menu matches 14 run scoreboard players reset @s ht_creative_menu

execute if score @s ht_creative_menu matches 15 run give @s minecraft:carrot_on_a_stick{horsetastic:{id:"blinky_whip"},CustomModelData:703002,display:{Name:"{\"text\":\"Whip\",\"color\":\"dark_purple\",\"italic\":\"false\"}",Lore:["{\"text\":\"Use to teleport to Blinky\",\"color\":\"dark_green\",\"italic\":\"false\"}"]},HideFlags:1,Enchantments:[{id:"minecraft:unbreaking",lvl:1}]} 1
execute if score @s ht_creative_menu matches 15 run scoreboard players reset @s ht_creative_menu
