#######
# Compiled from data/horsetastic/functions/creative_menu.mcscript
# to .//data/horsetastic/functions/creative_menu/menu.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tellraw @s {"text":""}
tellraw @s {"text":""}
tellraw @s [{"text":"<===== ","color":"aqua"},{"text":"Horsetastic","color":"red"},{"text":" =====>","color":"aqua"}]
tellraw @s {"text":""}
#Horse in a saddle
tellraw @s [{"text":"► ["},{"text":"1","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s ht_creative_menu 11"}},{"text":"]      ","color":"reset"},{"text":" ","color":"reset"},{"text":"Horse in a saddle"}]
#Skeleton Horse in a saddle
tellraw @s [{"text":"► ["},{"text":"1","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s ht_creative_menu 12"}},{"text":"]      ","color":"reset"},{"text":" ","color":"reset"},{"text":"Skeleton Horse in a saddle"}]
#Blinky's saddle
tellraw @s [{"text":"► ["},{"text":"1","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s ht_creative_menu 13"}},{"text":"]      ","color":"reset"},{"text":" ","color":"reset"},{"text":"Blinky's saddle"}]
#Whip
tellraw @s [{"text":"► ["},{"text":"1","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s ht_creative_menu 14"}},{"text":"]      ","color":"reset"},{"text":" ","color":"reset"},{"text":"Whip"}]
#Whip (Blinky)
tellraw @s [{"text":"► ["},{"text":"1","color":"green","clickEvent":{"action":"run_command","value":"/scoreboard players set @s ht_creative_menu 15"}},{"text":"]      ","color":"reset"},{"text":" ","color":"reset"},{"text":"Whip (Blinky)"}]
tellraw @s {"text":""}
tellraw @s [{"text":" ↑ ","color":"red"},{"text":"Return to main menu","hoverEvent":{"action":"show_text","value":"Click to return"},"clickEvent":{"action":"run_command","value":"/function unnamedde:creative_menu"}}]
tellraw @s {"text":""}
tellraw @s {"text":""}
