#######
# Compiled from data/horsetastic/functions/creative_menu.mcscript
# to .//data/horsetastic/functions/creative_menu/select.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tellraw @s [{"text":" ► ","color":"green"},{"text":"Horsetastic","hoverEvent":{"action":"show_text","value":"Click to select"},"clickEvent":{"action":"run_command","value":"/function horsetastic:creative_menu/menu"}}]
