#######
# Compiled from data/horsetastic/functions/give_whips.mcscript
# to .//data/horsetastic/functions/give_whips/basic.mcfunction
#
# Generated by Minecraft Script for 1.13
######
give @s minecraft:carrot_on_a_stick{CustomModelData:703001,display:{Lore:["{\"text\":\"Use to boost nearby horses\",\"color\":\"dark_green\",\"italic\":\"false\"}"],Name:"{\"text\":\"Whip\",\"color\":\"yellow\",\"italic\":\"false\"}"}} 1
