#######
# Compiled from /horsetastic/functions/give_whips.mcscript
# to .//horsetastic/functions/give_whips/blinky.mcfunction
#
# Generated by Minecraft Script for 1.13
######
give @s minecraft:carrot_on_a_stick{CustomModelData:703002,display:{Name:"{\"text\":\"Whip\",\"color\":\"dark_purple\",\"italic\":\"false\"}",Lore:["{\"text\":\"Use to teleport to Blinky\",\"color\":\"dark_green\",\"italic\":\"false\"}"]},HideFlags:1,Enchantments:[{id:"minecraft:unbreaking",lvl:1}]} 1