#######
# Compiled from data/horsetastic/functions/crafting.mcscript
# to .//data/horsetastic/functions/crafting/skeleton/1.mcfunction
#
# Generated by Minecraft Script for 1.13
######
replaceitem block ~ ~ ~ container.16 minecraft:saddle{horsetastic:{id:"skeleton_saddle"},display:{Name:"{\"text\":\"Skeleton Horse in a saddle\",\"color\":\"yellow\",\"italic\":false}",Lore:["{\"text\":\"Drop to summon a skeleton horse\",\"color\":\"dark_green\",\"italic\":false}"]},HideFlags:1,CustomModelData:703102,Enchantments:[{id:"minecraft:unbreaking",lvl:1}]} 1
tag @s add ac_lib_advanced_crafter_crafted
tag @s add ac_lib_advanced_crafter_crafted_saddle_skeleton
