#######
# Compiled from data/horsetastic/functions/whip.mcscript
# to .//data/horsetastic/functions/whip/basic.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @a[scores={horse_whip_used=1..}] at @s if entity @s[nbt={SelectedItem:{id: "minecraft:carrot_on_a_stick", Count: 1b, tag: {horsetastic:{id:"basic_whip"}}}}] run effect give @e[type=horse,distance=..5] minecraft:speed 2 4 true
execute as @a[scores={horse_whip_used=1..}] at @s if entity @s[nbt={SelectedItem:{id: "minecraft:carrot_on_a_stick", Count: 1b, tag: {horsetastic:{id:"basic_whip"}}}}] run playsound entity.generic.explode player @a ~ ~ ~ 1 1.75
execute as @a[scores={horse_whip_used=1..}] at @s if entity @s[nbt={SelectedItem:{id: "minecraft:carrot_on_a_stick", Count: 1b, tag: {horsetastic:{id:"basic_whip"}}}}] at @e[type=horse,limit=1,sort=nearest,distance=..5] rotated ~ 0 positioned ^ ^1.5 ^1 run particle minecraft:crit ~ ~ ~ 0 0 0 1 10
