#######
# Compiled from /horsetastic/functions/whip.mcscript
# to .//horsetastic/functions/whip/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function horsetastic:whip/basic
function horsetastic:whip/blinky


scoreboard players reset @a[scores={horse_whip_used=1..}] horse_whip_used
