#######
# Compiled from /horsetastic/functions/noai.mcscript
# to .//horsetastic/functions/noai/ai.mcfunction
#
# Generated by Minecraft Script for 1.13
######
data merge entity @s[tag=horsetastic_noai] {NoAI:0b}
tag @s remove horsetastic_noai
