#######
# Compiled from /horsetastic/functions/noai.mcscript
# to .//horsetastic/functions/noai/noai.mcfunction
#
# Generated by Minecraft Script for 1.13
######
data merge entity @s[tag=!horsetastic_noai] {NoAI:1b}
tag @s add horsetastic_noai