#######
# Compiled from /horsetastic/functions/give_extra.mcscript
# to .//horsetastic/functions/give/blinky_eye.mcfunction
#
# Generated by Minecraft Script for 1.13
######
give @s minecraft:ender_eye{CustomModelData:703202,display:{Name:"{\"text\":\"Eye of Blinky\",\"color\":\"dark_purple\",\"italic\":\"false\"}",Lore:["{\"text\":\"Used to craft Blinky's saddle\",\"color\":\"dark_green\",\"italic\":\"false\"}","{\"text\":\"Can also be used as an eye of ender\",\"color\":\"dark_green\",\"italic\":\"false\"}"]},HideFlags:1,Enchantments:[{id:"minecraft:unbreaking",lvl:1}]} 1