#######
# Compiled from data/horsetastic/functions/give_extra.mcscript
# to .//data/horsetastic/functions/give/undead_gem.mcfunction
#
# Generated by Minecraft Script for 1.13
######
give @s minecraft:emerald{HideFlags: 1, display: {Lore: ["{\"text\":\"Drops from zombies and skeletons\",\"color\":\"dark_green\",\"italic\":\"false\"}", "{\"text\":\"Used to create skeleton horse in a saddle\",\"color\":\"dark_green\",\"italic\":\"false\"}"], Name: "{\"text\":\"Gem of the Undead\",\"color\":\"yellow\",\"italic\":\"false\"}"}, Enchantments: [{lvl: 1, id: "minecraft:unbreaking"}]} 1