#######
# Compiled from data/horsetastic/functions/mark_saddles_og.mcscript
# to .//data/horsetastic/functions/mark_ground_saddles/basic.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[type=minecraft:item,nbt={Dimension: 0, OnGround: 1b, Item: {id: "minecraft:saddle", Count: 1b, tag: {CustomModelData:703101,HideFlags: 1, display: {Lore: ["{\"text\":\"Drop it on the ground to summon a horse\",\"color\":\"dark_green\",\"italic\":\"false\"}"], Name: "{\"text\":\"Horse in a saddle\",\"color\":\"yellow\",\"italic\":\"false\"}"}, Enchantments: [{lvl: 1, id: "minecraft:unbreaking"}]}}}] at @s run scoreboard players set @s saddle_type 1
