#######
# Compiled from data/horsetastic/functions/mark_saddles_og.mcscript
# to .//data/horsetastic/functions/mark_ground_saddles/basic.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[type=minecraft:item,nbt={Dimension:0,OnGround:1b,Item:{id:"minecraft:saddle",Count:1b,tag:{horsetastic:{id:"basic_saddle"}}}}] at @s run scoreboard players set @s saddle_type 1
