#######
# Compiled from /horsetastic/functions/mark_saddles_og.mcscript
# to .//horsetastic/functions/mark_ground_saddles/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function horsetastic:mark_ground_saddles/basic
function horsetastic:mark_ground_saddles/skeleton
function horsetastic:mark_ground_saddles/blinky
scoreboard players add @e[scores={saddle_type=1..},type=item] saddle_og 1
