#######
# Compiled from /horsetastic/functions/summon_horse_auto.mcscript
# to .//horsetastic/functions/summon_horse_auto/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######

function horsetastic:summon_horse_auto/basic
function horsetastic:summon_horse_auto/skeleton
function horsetastic:summon_horse_auto/blinky
