#######
# Compiled from data/horsetastic/functions/crafting.mcscript
# to .//data/horsetastic/functions/crafting/whip/basic.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute at @e[type=armor_stand,tag=aclib_craftingtable] if block ~ ~ ~ minecraft:dropper{Items:[{Slot: 2b, id: "minecraft:stick", Count: 1b}, {Slot: 4b, id: "minecraft:stick", Count: 1b}, {Slot: 5b, id: "minecraft:leather", Count: 1b}, {Slot: 6b, id: "minecraft:stick", Count: 1b}, {Slot: 8b, id: "minecraft:leather", Count: 1b}]} unless block ~ ~ ~ minecraft:dropper{Items:[{Slot:0b}]} unless block ~ ~ ~ minecraft:dropper{Items:[{Slot:1b}]} unless block ~ ~ ~ minecraft:dropper{Items:[{Slot:3b}]} unless block ~ ~ ~ minecraft:dropper{Items:[{Slot:7b}]} run data merge block ~ ~ ~ {Items:[{Slot:4b,id:"minecraft:carrot_on_a_stick",Count:1b,tag:{CustomModelData:703001,display:{Lore:["{\"text\":\"Use to boost nearby horses\",\"color\":\"dark_green\",\"italic\":\"false\"}"],Name:"{\"text\":\"Whip\",\"color\":\"yellow\",\"italic\":\"false\"}"}}}]}
