#######
# Compiled from data/horsetastic/functions/crafting.mcscript
# to .//data/horsetastic/functions/crafting/basic/action.mcfunction
#
# Generated by Minecraft Script for 1.13
######
tp @e[type=horse,limit=1,sort=nearest] ~ -500 ~
data merge entity @s {Item:{id:"minecraft:saddle",Count:1b,tag:{horsetastic:{id:"basic_saddle"},CustomModelData:703101,display:{Name:"{\"text\":\"Horse in a saddle\",\"color\":\"yellow\",\"italic\":\"false\"}",Lore:["{\"text\":\"Drop it on the ground to summon a horse\",\"color\":\"dark_green\",\"italic\":\"false\"}"]},HideFlags:1,Enchantments:[{id:"minecraft:unbreaking",lvl:1}]}}}
#log("finished")
