#######
# Compiled from data/horsetastic/functions/crafting.mcscript
# to .//data/horsetastic/functions/crafting/basic/detect.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute if entity @s[type=horse] as @e[distance=..1,type=minecraft:item_frame,nbt={Rotation: [0.0f, -90.0f], Item: {id: "minecraft:saddle", Count: 1b}}] at @s run function horsetastic:crafting/basic/action

