#######
# Compiled from data/horsetastic/functions/crafting.mcscript
# to .//data/horsetastic/functions/crafting/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function horsetastic:crafting/saddle
function horsetastic:crafting/skeleton
function horsetastic:crafting/whip/basic
function horsetastic:crafting/whip/blinky

execute as @e[type=minecraft:item_frame,nbt={Rotation: [0.0f, -90.0f], Item: {id: "minecraft:saddle", Count: 1b}}] at @s if entity @e[distance=..1,type=horse,tag=smash_anvil] run function horsetastic:crafting/basic
