#######
# Compiled from /horsetastic/functions/visuals.mcscript
# to .//horsetastic/functions/visuals/blinky.mcfunction
#
# Generated by Minecraft Script for 1.13
######
execute as @e[type=minecraft:skeleton_horse,tag=horsetastic_horse_blinky] at @s positioned ^ ^ ^1.2 run particle minecraft:flame ~ ~1.6 ~ 0.1 0.1 0.1 0 1 force