#######
# Compiled from /horsetastic/functions/visuals.mcscript
# to .//horsetastic/functions/visuals/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
function horsetastic:visuals/blinky
