#######
# Compiled from data/horsetastic/functions/visuals.mcscript
# to .//data/horsetastic/functions/visuals/saddle.mcfunction
#
# Generated by Minecraft Script for 1.13
######
particle minecraft:lava ~ ~ ~ 0.1 0 0.1 1 1
