#######
# Compiled from /horsetastic/functions/visuals.mcscript
# to .//horsetastic/functions/visuals/summon.mcfunction
#
# Generated by Minecraft Script for 1.13
######
particle poof ~ ~ ~ 0 0 0 1 100 normal
playsound minecraft:entity.horse.armor neutral @a ~ ~ ~
