#######
# Compiled from /horsetastic/functions/visuals.mcscript
# to .//horsetastic/functions/visuals/tp.mcfunction
#
# Generated by Minecraft Script for 1.13
######
particle minecraft:portal ~ ~ ~ 0 0 0 10 500
playsound minecraft:entity.enderman.teleport player @a ~ ~ ~
