#######
# Compiled from data/horsetastic/functions/visuals.mcscript
# to .//data/horsetastic/functions/visuals/tp_away.mcfunction
#
# Generated by Minecraft Script for 1.13
######
particle minecraft:portal ~ ~.5 ~ 0 0 0 1 100
playsound minecraft:entity.enderman.teleport neutral @a ~ ~ ~
