#######
# Compiled from data/horsetastic/functions/crafting.mcscript
# to .//data/horsetastic/functions/crafting/whip/basic/1.mcfunction
#
# Generated by Minecraft Script for 1.13
######
replaceitem block ~ ~ ~ container.16 minecraft:carrot_on_a_stick{CustomModelData:703001,display:{Lore:["{\"text\":\"Use to boost nearby horses\",\"color\":\"dark_green\",\"italic\":\"false\"}"],Name:"{\"text\":\"Whip\",\"color\":\"yellow\",\"italic\":\"false\"}"},horsetastic:{id:"basic_whip"}} 1
tag @s add ac_lib_advanced_crafter_crafted
tag @s add ac_lib_advanced_crafter_crafted_basic_whip
