#######
# Compiled from data/horsetastic/functions/replace_saddles.mcscript
# to .//data/horsetastic/functions/replace_saddles/player/basic.mcfunction
#
# Generated by Minecraft Script for 1.13
######
give @s minecraft:wooden_sword{Placeholder:1} 36
kill @e[type=item,nbt={Item:{id:"minecraft:wooden_sword",tag:{Placeholder:1}}}]
clear @s minecraft:saddle{CustomModelData:703101,HideFlags: 1, display: {Lore: ["{\"text\":\"Remove to pick up the horse\",\"color\":\"dark_green\",\"italic\":\"false\"}"], Name: "{\"text\":\"Horse in a saddle's saddle\",\"color\":\"yellow\",\"italic\":\"false\"}"}, Enchantments: [{lvl: 1, id: "minecraft:unbreaking"}]} 1
function horsetastic:give_saddle/basic
clear @s minecraft:wooden_sword{Placeholder:1} 36
