#######
# Compiled from /horsetastic/functions/replace_saddles.mcscript
# to .//horsetastic/functions/replace_saddles/player/blinky.mcfunction
#
# Generated by Minecraft Script for 1.13
######
give @s minecraft:wooden_sword{Placeholder:1} 36
kill @e[type=item,nbt={Item:{id:"minecraft:wooden_sword",tag:{Placeholder:1}}}]
clear @s minecraft:saddle{CustomModelData:703103,display:{Name:"{\"text\":\"Blinky's saddle\",\"color\":\"dark_purple\",\"italic\":\"false\"}",Lore:["{\"text\":\"Remove to pick up Blinky\",\"color\":\"dark_green\",\"italic\":\"false\"}"]},HideFlags:1,Enchantments:[{id:"minecraft:unbreaking",lvl:1}]} 1
function horsetastic:give_saddle/blinky
clear @s minecraft:wooden_sword{Placeholder:1} 36
