#######
# Compiled from data/horsetastic/functions/replace_saddles.mcscript
# to .//data/horsetastic/functions/replace_saddles/player/blinky.mcfunction
#
# Generated by Minecraft Script for 1.13
######
clear @s minecraft:saddle{horsetastic:{id:"blinky_saddle_"}} 1
scoreboard players set @s ht_creative_menu 13
