#######
# Compiled from data/horsetastic/functions/replace_saddles.mcscript
# to .//data/horsetastic/functions/replace_saddles/player/skeleton.mcfunction
#
# Generated by Minecraft Script for 1.13
######
give @s minecraft:wooden_sword{Placeholder:1} 36
kill @e[type=item,nbt={Item:{id:"minecraft:wooden_sword",tag:{Placeholder:1}}}]
clear @s minecraft:saddle{CustomModelData:703102,display:{Name:"{\"text\":\"Skeleton Horse's saddle\",\"color\":\"yellow\",\"italic\":\"false\"}",Lore:["{\"text\":\"Remove to pick up the skeleton horse\",\"color\":\"dark_green\",\"italic\":\"false\"}"]},HideFlags:1,Enchantments:[{id:"minecraft:unbreaking",lvl:1}]} 1
function horsetastic:give_saddle/skeleton
clear @s minecraft:wooden_sword{Placeholder:1} 36
