#######
# Compiled from data/horsetastic/functions/replace_saddles.mcscript
# to .//data/horsetastic/functions/replace_saddles/player/skeleton.mcfunction
#
# Generated by Minecraft Script for 1.13
######
clear @s minecraft:saddle{horsetastic:{id:"skeleton_saddle_"}} 1
scoreboard players set @s ht_creative_menu 12
