#######
# Compiled from /horsetastic/functions/give_saddles.mcscript
# to .//horsetastic/functions/give_saddle/basic.mcfunction
#
# Generated by Minecraft Script for 1.13
######
give @s minecraft:saddle{CustomModelData:703101,display:{Name:"{\"text\":\"Horse in a saddle\",\"color\":\"yellow\",\"italic\":\"false\"}",Lore:["{\"text\":\"Drop it on the ground to summon a horse\",\"color\":\"dark_green\",\"italic\":\"false\"}"]},HideFlags:1,Enchantments:[{id:"minecraft:unbreaking",lvl:1}]} 1
