#######
# Compiled from data/horsetastic/functions/give_saddles.mcscript
# to .//data/horsetastic/functions/give_saddle/blinky.mcfunction
#
# Generated by Minecraft Script for 1.13
######
give @p minecraft:saddle{CustomModelData:703103,display:{Name:"{\"text\":\"Blinky's saddle\",\"color\":\"dark_purple\",\"italic\":\"false\"}",Lore:["{\"text\":\"Drop to summon Blinky\",\"color\":\"dark_green\",\"italic\":\"false\"}"]},HideFlags:1,Enchantments:[{id:"minecraft:unbreaking",lvl:1}]} 1