#######
# Compiled from data/horsetastic/functions/give_saddles.mcscript
# to .//data/horsetastic/functions/give_saddle/skeleton.mcfunction
#
# Generated by Minecraft Script for 1.13
######
give @p minecraft:saddle{CustomModelData:703102,display:{Name:"{\"text\":\"Skeleton Horse in a saddle\",\"color\":\"yellow\",\"italic\":\"false\"}",Lore:["{\"text\":\"Drop to summon a skeleton horse\",\"color\":\"dark_green\",\"italic\":\"false\"}"]},HideFlags:1,Enchantments:[{id:"minecraft:unbreaking",lvl:1}]} 1
