#######
# Compiled from /horsetastic/functions/replace_saddles.mcscript
# to .//horsetastic/functions/replace_saddles/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
#basic
execute as @a[nbt={Inventory: [{id: "minecraft:saddle", Count: 1b, tag: {CustomModelData:703101,HideFlags: 1, display: {Lore: ["{\"text\":\"Remove to pick up the horse\",\"color\":\"dark_green\",\"italic\":\"false\"}"], Name: "{\"text\":\"Horse in a saddle's saddle\",\"color\":\"yellow\",\"italic\":\"false\"}"}, Enchantments: [{lvl: 1, id: "minecraft:unbreaking"}]}}]}] at @s run function horsetastic:replace_saddles/player/basic
execute as @e[type=minecraft:item,nbt={Item: {id: "minecraft:saddle", Count: 1b, tag: {CustomModelData:703101,HideFlags: 1, display: {Lore: ["{\"text\":\"Remove to pick up the horse\",\"color\":\"dark_green\",\"italic\":\"false\"}"], Name: "{\"text\":\"Horse in a saddle's saddle\",\"color\":\"yellow\",\"italic\":\"false\"}"}, Enchantments: [{lvl: 1, id: "minecraft:unbreaking"}]}}}] at @s run function horsetastic:replace_saddles/ground/basic

#skeleton
execute as @a[nbt={Inventory: [{id: "minecraft:saddle", Count: 1b, tag: {CustomModelData:703102,HideFlags: 1, display: {Lore: ["{\"text\":\"Remove to pick up the skeleton horse\",\"color\":\"dark_green\",\"italic\":\"false\"}"], Name: "{\"text\":\"Skeleton Horse's saddle\",\"color\":\"yellow\",\"italic\":\"false\"}"}, Enchantments: [{lvl: 1, id: "minecraft:unbreaking"}]}}]}] at @s run function horsetastic:replace_saddles/player/skeleton
execute as @e[type=minecraft:item,nbt={Item: {id: "minecraft:saddle", Count: 1b, tag: {CustomModelData:703102,display:{Name:"{\"text\":\"Skeleton Horse's saddle\",\"color\":\"yellow\",\"italic\":\"false\"}",Lore:["{\"text\":\"Remove to pick up the skeleton horse\",\"color\":\"dark_green\",\"italic\":\"false\"}"]},HideFlags:1,Enchantments:[{id:"minecraft:unbreaking",lvl:1}]}}}] at @s run function horsetastic:replace_saddles/ground/skeleton

#blinky
execute as @a[nbt={Inventory: [{id: "minecraft:saddle", Count: 1b, tag: {CustomModelData:703103,HideFlags: 1, display: {Lore: ["{\"text\":\"Remove to pick up Blinky\",\"color\":\"dark_green\",\"italic\":\"false\"}"], Name: "{\"text\":\"Blinky's saddle\",\"color\":\"dark_purple\",\"italic\":\"false\"}"}, Enchantments: [{lvl: 1, id: "minecraft:unbreaking"}]}}]}] at @s run function horsetastic:replace_saddles/player/blinky
execute as @e[type=minecraft:item,nbt={Item: {id: "minecraft:saddle", Count: 1b, tag: {CustomModelData:703103,HideFlags: 1, display: {Lore: ["{\"text\":\"Remove to pick up Blinky\",\"color\":\"dark_green\",\"italic\":\"false\"}"], Name: "{\"text\":\"Blinky's saddle\",\"color\":\"dark_purple\",\"italic\":\"false\"}"}, Enchantments: [{lvl: 1, id: "minecraft:unbreaking"}]}}}] at @s run function horsetastic:replace_saddles/ground/blinky
