#######
# Compiled from data/horsetastic/functions/replace_saddles.mcscript
# to .//data/horsetastic/functions/replace_saddles/main.mcfunction
#
# Generated by Minecraft Script for 1.13
######
#basic
execute as @a[nbt={Inventory: [{id: "minecraft:saddle", Count: 1b, tag: {horsetastic:{id:"basic_saddle_"}}}]}] at @s run function horsetastic:replace_saddles/player/basic
execute as @e[type=minecraft:item,nbt={Item: {id: "minecraft:saddle", Count: 1b, tag: {horsetastic:{id:"basic_saddle_"}}}}] at @s run function horsetastic:replace_saddles/ground/basic

#skeleton
execute as @a[nbt={Inventory: [{id: "minecraft:saddle", Count: 1b, tag: {horsetastic:{id:"skeleton_saddle_"}}}]}] at @s run function horsetastic:replace_saddles/player/skeleton
execute as @e[type=minecraft:item,nbt={Item: {id: "minecraft:saddle", Count: 1b, tag: {horsetastic:{id:"skeleton_saddle_"}}}}] at @s run function horsetastic:replace_saddles/ground/skeleton

#blinky
execute as @a[nbt={Inventory: [{id: "minecraft:saddle", Count: 1b, tag: {horsetastic:{id:"blinky_saddle_"}}}]}] at @s run function horsetastic:replace_saddles/player/blinky
execute as @e[type=minecraft:item,nbt={Item: {id: "minecraft:saddle", Count: 1b, tag: {horsetastic:{id:"blinky_saddle_"}}}}] at @s run function horsetastic:replace_saddles/ground/blinky
